image: nabukatnazar/maven_sonarscan:0.0.1

stages:
  - build
  - test
  - sonar
  - runGauge

build:
  stage: build
  script:
    - echo "Building project ..."
    - mvn clean compile
test:
  stage: test
  script:
    - echo "Running Maven tests ..."
    - mvn test
sonar:
  stage: sonar
  before_script:
    - echo "Sonar Scanner Installation..."
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.1.2450-linux.zip
    - unzip sonar-scanner-cli-4.6.1.2450-linux.zip
    - chmod +x sonar-scanner-4.6.1.2450-linux/bin/sonar-scanner
  script:
    - echo "Running Maven tests and code analyses on sonarqube ..."
    - mvn compile test
    - ./sonar-scanner-4.6.1.2450-linux/bin/sonar-scanner -Dsonar.projectKey=gitlab-demo -Dsonar.host.url=http://sonar.testinium.com -Dsonar.login=56e2166a26beac601a9a1c5db9380d389bc6861c -Dsonar.language=java -Dsonar.java.binaries=target/test-classes
runGauge:
  stage: runGauge
  script:
    - echo "Sonar analysis is finished. Running gauge project..."
    - sh runGaugeConf.sh
